In [1]:
import pandas as pd

In [2]:
pd.options.display.max_colwidth=300

In [3]:
crossfitDF=pd.read_csv("women_open_21.1.csv")
crossfitDF

,Unnamed: 0,first_name,lastname,Placing,country,continent,Age,affiliate,Height and Weight,points,21.1,21.1 time,21.2,21.2 time,21.3,21.3 time,21.4,weight
0,0,TIA-CLAIR,TOOMEY,1,Australia,Oceania,Age 27,CrossFit East Nashville,163 cm | 58 kg,26,6th (11:21),605 reps,11th (9:26),225 reps,1st (7:37),180 reps,8th (230 lbs),Weight lifted: 230 lbs.
1,1,EMMA,CARY,2,United States,North America,Age 17,Perform Overcome Excel CrossFit,64 in | 140 lb,66,14th (11:48),605 reps,1st (8:51),225 reps,14th (8:28),180 reps,37th (218 lbs),Weight lifted: 218 lbs.
2,2,KARA,SAUNDERS,3,Australia,Oceania,Age 31,CrossFit Carv,162 cm | 158 lb,111,63rd (13:11),605 reps,23rd (9:42),225 reps,20th (8:41),180 reps,5th (232 lbs),Weight lifted: 232 lbs.
3,3,KRISTI ERAMO,O'CONNELL,4,United States,North America,Age 32,CrossFit Polaris,62 in | 132 lb,189,121st (13:47),605 reps,21st (9:41),225 reps,4th (7:47),180 reps,43rd (217 lbs),Weight lifted: 217 lbs.
4,4,MALLORY,O'BRIEN,5,United States,North America,Age 17,Lion Brave CrossFit,63 in | 145 lb,211,4th (11:06),605 reps,163rd (10:38),225 reps,2nd (7:38),180 reps,42nd (217 lbs),Weight lifted: 217 lbs.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108595,108595,GEORGINA,NOELLEN,108565,Germany,Europe,Age 32,CrossFit Neuss,166 cm | 54 kg,374151,94308th (--),NaN,90537th (--),NaN,80806th (--),NaN,108500th (--),NaN
108596,108596,STACEY,MAIDA,108565,United States,North America,Age 36,CrossFit Five Points,65 in | 172 lb,374151,94308th (--),NaN,90537th (--),NaN,80806th (--),NaN,108500th (--),NaN
108597,108597,FIONA,STEEL,108565,United Kingdom,Europe,Age 31,NaN,NaN,374151,94308th (--),NaN,90537th (--),NaN,80806th (--),NaN,108500th (--),NaN
108598,108598,RACHAEL,BUTLER,108565,Canada,North America,Age 34,NaN,130 lb,374151,94308th (--),NaN,90537th (--),NaN,80806th (--),NaN,108500th (--),NaN
108599,108599,VALERIA,MONTERO,108565,United States,North America,Age 21,NaN,60 in,374151,94308th (--),NaN,90537th (--),NaN,80806th (--),NaN,108500th (--),NaN

In [4]:
crossfitDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108600 entries, 0 to 108599
Data columns (total 18 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         108600 non-null  int64
 1   first_name         108599 non-null  object
 2   lastname           108597 non-null  object
 3   Placing            108600 non-null  int64
 4   country            108600 non-null  object
 5   continent          108600 non-null  object
 6   Age                108600 non-null  object
 7   affiliate          93538 non-null   object
 8   Height and Weight  50325 non-null   object
 9   points             108600 non-null  int64
 10  21.1               108600 non-null  object
 11  21.1 time          8349 non-null    object
 12  21.2               108600 non-null  object
 13  21.2 time          50690 non-null   object
 14  21.3               108600 non-null  object
 15  21.3 time          8209 non-null    object
 16  21.4               108600 non-null  object
 17  weight             80318 non-null   object
dtypes: int64(3), object(15)
memory usage: 14.9+ MB

In [5]:
del crossfitDF["Unnamed: 0"]

In [6]:
crossfitDF.rename(columns={
    '21.1': '21.1 Scores',
    '21.2': '21.2 Scores',
    '21.3': '21.3 Scores',
    '21.4': '21.4 Scores'
}, inplace=True)

In [7]:
crossfitDF['first_name'] = crossfitDF['first_name'].str.title()
crossfitDF['lastname'] = crossfitDF['lastname'].str.title()

In [8]:
crossfitDF.head()

,first_name,lastname,Placing,country,continent,Age,affiliate,Height and Weight,points,21.1 Scores,21.1 time,21.2 Scores,21.2 time,21.3 Scores,21.3 time,21.4 Scores,weight
0,Tia-Clair,Toomey,1,Australia,Oceania,Age 27,CrossFit East Nashville,163 cm | 58 kg,26,6th (11:21),605 reps,11th (9:26),225 reps,1st (7:37),180 reps,8th (230 lbs),Weight lifted: 230 lbs.
1,Emma,Cary,2,United States,North America,Age 17,Perform Overcome Excel CrossFit,64 in | 140 lb,66,14th (11:48),605 reps,1st (8:51),225 reps,14th (8:28),180 reps,37th (218 lbs),Weight lifted: 218 lbs.
2,Kara,Saunders,3,Australia,Oceania,Age 31,CrossFit Carv,162 cm | 158 lb,111,63rd (13:11),605 reps,23rd (9:42),225 reps,20th (8:41),180 reps,5th (232 lbs),Weight lifted: 232 lbs.
3,Kristi Eramo,O'Connell,4,United States,North America,Age 32,CrossFit Polaris,62 in | 132 lb,189,121st (13:47),605 reps,21st (9:41),225 reps,4th (7:47),180 reps,43rd (217 lbs),Weight lifted: 217 lbs.
4,Mallory,O'Brien,5,United States,North America,Age 17,Lion Brave CrossFit,63 in | 145 lb,211,4th (11:06),605 reps,163rd (10:38),225 reps,2nd (7:38),180 reps,42nd (217 lbs),Weight lifted: 217 lbs.

In [9]:
crossfitDF[['Height', 'Weight']] = crossfitDF['Height and Weight'].str.split("|", expand = True)
crossfitDF.head()

,first_name,lastname,Placing,country,continent,Age,affiliate,Height and Weight,points,21.1 Scores,21.1 time,21.2 Scores,21.2 time,21.3 Scores,21.3 time,21.4 Scores,weight,Height,Weight
0,Tia-Clair,Toomey,1,Australia,Oceania,Age 27,CrossFit East Nashville,163 cm | 58 kg,26,6th (11:21),605 reps,11th (9:26),225 reps,1st (7:37),180 reps,8th (230 lbs),Weight lifted: 230 lbs.,163 cm,58 kg
1,Emma,Cary,2,United States,North America,Age 17,Perform Overcome Excel CrossFit,64 in | 140 lb,66,14th (11:48),605 reps,1st (8:51),225 reps,14th (8:28),180 reps,37th (218 lbs),Weight lifted: 218 lbs.,64 in,140 lb
2,Kara,Saunders,3,Australia,Oceania,Age 31,CrossFit Carv,162 cm | 158 lb,111,63rd (13:11),605 reps,23rd (9:42),225 reps,20th (8:41),180 reps,5th (232 lbs),Weight lifted: 232 lbs.,162 cm,158 lb
3,Kristi Eramo,O'Connell,4,United States,North America,Age 32,CrossFit Polaris,62 in | 132 lb,189,121st (13:47),605 reps,21st (9:41),225 reps,4th (7:47),180 reps,43rd (217 lbs),Weight lifted: 217 lbs.,62 in,132 lb
4,Mallory,O'Brien,5,United States,North America,Age 17,Lion Brave CrossFit,63 in | 145 lb,211,4th (11:06),605 reps,163rd (10:38),225 reps,2nd (7:38),180 reps,42nd (217 lbs),Weight lifted: 217 lbs.,63 in,145 lb

In [10]:
#del crossfitDF['Height and Weight']

crossfitDF.rename(columns={
    'first_name': 'First Name',
    'lastname': 'Last Name',
    'country': 'Country',
    'continent': 'Continent',
    'affiliate': 'Affiliate',
    'points': 'Points',
    '21.1 time': '21.1 Reps',
    '21.2 time': '21.2 Reps',
    '21.3 time': '21.3 Reps',
    'weight': 'Weight Lifted'
}, inplace=True)
crossfitDF.head()

,First Name,Last Name,Placing,Country,Continent,Age,Affiliate,Height and Weight,Points,21.1 Scores,21.1 Reps,21.2 Scores,21.2 Reps,21.3 Scores,21.3 Reps,21.4 Scores,Weight Lifted,Height,Weight
0,Tia-Clair,Toomey,1,Australia,Oceania,Age 27,CrossFit East Nashville,163 cm | 58 kg,26,6th (11:21),605 reps,11th (9:26),225 reps,1st (7:37),180 reps,8th (230 lbs),Weight lifted: 230 lbs.,163 cm,58 kg
1,Emma,Cary,2,United States,North America,Age 17,Perform Overcome Excel CrossFit,64 in | 140 lb,66,14th (11:48),605 reps,1st (8:51),225 reps,14th (8:28),180 reps,37th (218 lbs),Weight lifted: 218 lbs.,64 in,140 lb
2,Kara,Saunders,3,Australia,Oceania,Age 31,CrossFit Carv,162 cm | 158 lb,111,63rd (13:11),605 reps,23rd (9:42),225 reps,20th (8:41),180 reps,5th (232 lbs),Weight lifted: 232 lbs.,162 cm,158 lb
3,Kristi Eramo,O'Connell,4,United States,North America,Age 32,CrossFit Polaris,62 in | 132 lb,189,121st (13:47),605 reps,21st (9:41),225 reps,4th (7:47),180 reps,43rd (217 lbs),Weight lifted: 217 lbs.,62 in,132 lb
4,Mallory,O'Brien,5,United States,North America,Age 17,Lion Brave CrossFit,63 in | 145 lb,211,4th (11:06),605 reps,163rd (10:38),225 reps,2nd (7:38),180 reps,42nd (217 lbs),Weight lifted: 217 lbs.,63 in,145 lb

In [11]:
#del crossfitDF['Height and Weight']
#crossfitDF['Age'] = crossfitDF['Age'].str.replace('Age ', '')
#crossfitDF['Weight Lifted'] = crossfitDF['Weight Lifted'].str.replace('Weight lifted: ', '')
crossfitDF['21.1 Reps'] = crossfitDF['21.1 Reps'].str.replace("reps", '')
crossfitDF['21.2 Reps'] = crossfitDF['21.2 Reps'].str.replace("reps", '')
crossfitDF['21.3 Reps'] = crossfitDF['21.3 Reps'].str.replace("reps", '')
crossfitDF.head()

,First Name,Last Name,Placing,Country,Continent,Age,Affiliate,Height and Weight,Points,21.1 Scores,21.1 Reps,21.2 Scores,21.2 Reps,21.3 Scores,21.3 Reps,21.4 Scores,Weight Lifted,Height,Weight
0,Tia-Clair,Toomey,1,Australia,Oceania,Age 27,CrossFit East Nashville,163 cm | 58 kg,26,6th (11:21),605,11th (9:26),225,1st (7:37),180,8th (230 lbs),Weight lifted: 230 lbs.,163 cm,58 kg
1,Emma,Cary,2,United States,North America,Age 17,Perform Overcome Excel CrossFit,64 in | 140 lb,66,14th (11:48),605,1st (8:51),225,14th (8:28),180,37th (218 lbs),Weight lifted: 218 lbs.,64 in,140 lb
2,Kara,Saunders,3,Australia,Oceania,Age 31,CrossFit Carv,162 cm | 158 lb,111,63rd (13:11),605,23rd (9:42),225,20th (8:41),180,5th (232 lbs),Weight lifted: 232 lbs.,162 cm,158 lb
3,Kristi Eramo,O'Connell,4,United States,North America,Age 32,CrossFit Polaris,62 in | 132 lb,189,121st (13:47),605,21st (9:41),225,4th (7:47),180,43rd (217 lbs),Weight lifted: 217 lbs.,62 in,132 lb
4,Mallory,O'Brien,5,United States,North America,Age 17,Lion Brave CrossFit,63 in | 145 lb,211,4th (11:06),605,163rd (10:38),225,2nd (7:38),180,42nd (217 lbs),Weight lifted: 217 lbs.,63 in,145 lb

In [12]:
crossfitDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108600 entries, 0 to 108599
Data columns (total 19 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   First Name         108599 non-null  object
 1   Last Name          108597 non-null  object
 2   Placing            108600 non-null  int64
 3   Country            108600 non-null  object
 4   Continent          108600 non-null  object
 5   Age                108600 non-null  object
 6   Affiliate          93538 non-null   object
 7   Height and Weight  50325 non-null   object
 8   Points             108600 non-null  int64
 9   21.1 Scores        108600 non-null  object
 10  21.1 Reps          8349 non-null    object
 11  21.2 Scores        108600 non-null  object
 12  21.2 Reps          50690 non-null   object
 13  21.3 Scores        108600 non-null  object
 14  21.3 Reps          8209 non-null    object
 15  21.4 Scores        108600 non-null  object
 16  Weight Lifted      80318 non-null   object
 17  Height             50325 non-null   object
 18  Weight             41489 non-null   object
dtypes: int64(2), object(17)
memory usage: 15.7+ MB

In [13]:
crossfitDF['Age'] = crossfitDF['Age'].str.replace("Age", '')
crossfitDF['Age'] = crossfitDF['Age'].astype(int)
crossfitDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108600 entries, 0 to 108599
Data columns (total 19 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   First Name         108599 non-null  object
 1   Last Name          108597 non-null  object
 2   Placing            108600 non-null  int64
 3   Country            108600 non-null  object
 4   Continent          108600 non-null  object
 5   Age                108600 non-null  int32
 6   Affiliate          93538 non-null   object
 7   Height and Weight  50325 non-null   object
 8   Points             108600 non-null  int64
 9   21.1 Scores        108600 non-null  object
 10  21.1 Reps          8349 non-null    object
 11  21.2 Scores        108600 non-null  object
 12  21.2 Reps          50690 non-null   object
 13  21.3 Scores        108600 non-null  object
 14  21.3 Reps          8209 non-null    object
 15  21.4 Scores        108600 non-null  object
 16  Weight Lifted      80318 non-null   object
 17  Height             50325 non-null   object
 18  Weight             41489 non-null   object
dtypes: int32(1), int64(2), object(16)
memory usage: 15.3+ MB

In [14]:
crossfitDF = crossfitDF.dropna(how='any')

In [22]:
crossfitDF.head(10)
crossfitDF.tail(10)

,First Name,Last Name,Placing,Country,Continent,Age,Affiliate,Height and Weight,Points,21.1 Scores,21.1 Reps,21.2 Scores,21.2 Reps,21.3 Scores,21.3 Reps,21.4 Scores,Weight Lifted,Height,Weight
93334,Kimberly,Wong,93335,Canada,North America,32,CrossFit Green,65 in | 150 lb,338502,91409th (12:36 - f),605,88695th (14:05 - f),225,78599th (9:05 - f),180,79799th (17 lbs - f),Weight lifted: 17 lbs.,65 in,150 lb
93408,Mandy-Leigh,Hackart,93409,Australia,Oceania,36,CrossFit 4504,159 cm | 63 kg,338665,91515th (13:18 - f),605,88575th (13:19 - f),225,78821st (9:27 - f),180,79754th (22 lbs - f),Weight lifted: 22 lbs.,159 cm,63 kg
93426,Charlotte,Cox,93427,United Kingdom,Europe,33,CrossFit Leyland,164 cm | 66 kg,338692,91602nd (13:47 - f),605,88404th (12:14 - f),225,79031st (9:51 - f),180,79655th (33 lbs - f),Weight lifted: 33 lbs.,164 cm,66 kg
93496,Birgit,Baldauf,93497,Germany,Europe,46,CrossFit Rhein-Neckar,173 cm | 67 kg,338850,91588th (13:43 - f),605,88323rd (11:41 - f),225,79003rd (9:48 - f),180,79936th (1 lbs - f),Weight lifted: 1 lbs.,173 cm,67 kg
93515,Victoria,Michel,93516,United States,North America,34,CrossFit Stony Brook,69 in | 145 lb,338892,91165th (9:23 - f),605,88152nd (10:24 - f),225,79945th (13:14 - f),180,79630th (35 lbs - f),Weight lifted: 35 lbs.,69 in,145 lb
93906,Laetitia,Decraene,93907,France,Europe,35,MKB CrossFit,170 cm | 69 kg,339829,91360th (12:17 - f),605,89232nd (17:28 - f),225,79392nd (10:40 - f),180,79845th (13 lbs - f),Weight lifted: 13 lbs.,170 cm,69 kg
93995,Sille,Vaiksaar,93996,Estonia,Europe,37,CrossFit Tartu,174 cm | 68 kg,340095,91749th (14:32 - f),605,88558th (13:14 - f),225,79979th (13:31 - f),180,79809th (16 lbs - f),Weight lifted: 16 lbs.,174 cm,68 kg
95263,Maria,Wheeler,95263,United States,North America,54,Wild Horizons CrossFit,63 in | 157 lb,344295,91725th (14:25 - f),605,88988th (15:49 - f),225,79071st (9:56 - f),180,84511th (0 lbs - f),Weight lifted: 0 lbs.,63 in,157 lb
100420,Stella,Richards,100421,United States,North America,17,Badger CrossFit,67 in | 140 lb,356203,91795th (14:44 - f),605,88760th (14:29 - f),225,78698th (9:14 - f),180,96950th (0 lbs - f),Weight lifted: 0 lbs.,67 in,140 lb
102709,Sarah,Carter,102710,United Kingdom,Europe,35,CW1 CrossFit,168 cm | 59 kg,361337,91650th (14:04 - f),605,88356th (11:55 - f),225,76824th (6:45 - f),180,104507th (0 lbs - f),Weight lifted: 0 lbs.,168 cm,59 kg

In [26]:
#crossfitDF['21.3 Reps'] = crossfitDF['21.3 Reps'].str.replace("1 front squat", '')
# ?? 
crossfitDF2 = crossfitDF[crossfitDF['21.3 Reps'].str.contains("1 front squat")==False]
crossfitDF2

,First Name,Last Name,Placing,Country,Continent,Age,Affiliate,Height and Weight,Points,21.1 Scores,21.1 Reps,21.2 Scores,21.2 Reps,21.3 Scores,21.3 Reps,21.4 Scores,Weight Lifted,Height,Weight
0,Tia-Clair,Toomey,1,Australia,Oceania,27,CrossFit East Nashville,163 cm | 58 kg,26,6th (11:21),605,11th (9:26),225,1st (7:37),180,8th (230 lbs),Weight lifted: 230 lbs.,163 cm,58 kg
1,Emma,Cary,2,United States,North America,17,Perform Overcome Excel CrossFit,64 in | 140 lb,66,14th (11:48),605,1st (8:51),225,14th (8:28),180,37th (218 lbs),Weight lifted: 218 lbs.,64 in,140 lb
2,Kara,Saunders,3,Australia,Oceania,31,CrossFit Carv,162 cm | 158 lb,111,63rd (13:11),605,23rd (9:42),225,20th (8:41),180,5th (232 lbs),Weight lifted: 232 lbs.,162 cm,158 lb
3,Kristi Eramo,O'Connell,4,United States,North America,32,CrossFit Polaris,62 in | 132 lb,189,121st (13:47),605,21st (9:41),225,4th (7:47),180,43rd (217 lbs),Weight lifted: 217 lbs.,62 in,132 lb
4,Mallory,O'Brien,5,United States,North America,17,Lion Brave CrossFit,63 in | 145 lb,211,4th (11:06),605,163rd (10:38),225,2nd (7:38),180,42nd (217 lbs),Weight lifted: 217 lbs.,63 in,145 lb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93906,Laetitia,Decraene,93907,France,Europe,35,MKB CrossFit,170 cm | 69 kg,339829,91360th (12:17 - f),605,89232nd (17:28 - f),225,79392nd (10:40 - f),180,79845th (13 lbs - f),Weight lifted: 13 lbs.,170 cm,69 kg
93995,Sille,Vaiksaar,93996,Estonia,Europe,37,CrossFit Tartu,174 cm | 68 kg,340095,91749th (14:32 - f),605,88558th (13:14 - f),225,79979th (13:31 - f),180,79809th (16 lbs - f),Weight lifted: 16 lbs.,174 cm,68 kg
95263,Maria,Wheeler,95263,United States,North America,54,Wild Horizons CrossFit,63 in | 157 lb,344295,91725th (14:25 - f),605,88988th (15:49 - f),225,79071st (9:56 - f),180,84511th (0 lbs - f),Weight lifted: 0 lbs.,63 in,157 lb
100420,Stella,Richards,100421,United States,North America,17,Badger CrossFit,67 in | 140 lb,356203,91795th (14:44 - f),605,88760th (14:29 - f),225,78698th (9:14 - f),180,96950th (0 lbs - f),Weight lifted: 0 lbs.,67 in,140 lb
102709,Sarah,Carter,102710,United Kingdom,Europe,35,CW1 CrossFit,168 cm | 59 kg,361337,91650th (14:04 - f),605,88356th (11:55 - f),225,76824th (6:45 - f),180,104507th (0 lbs - f),Weight lifted: 0 lbs.,168 cm,59 kg

In [25]:
test = crossfitDF['21.3 Reps']
print(test)

0         180
1         180
2         180
3         180
4         180
          ...
93906     180
93995     180
95263     180
100420    180
102709    180
Name: 21.3 Reps, Length: 492, dtype: object

In [29]:
crossfitDF2['21.1 Reps'] = crossfitDF2['21.1 Reps'].astype(int)
crossfitDF2['21.2 Reps'] = crossfitDF2['21.2 Reps'].astype(int)
crossfitDF2['21.3 Reps'] = crossfitDF2['21.3 Reps'].astype(int)
crossfitDF2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 491 entries, 0 to 102709
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         491 non-null    object
 1   Last Name          491 non-null    object
 2   Placing            491 non-null    int64
 3   Country            491 non-null    object
 4   Continent          491 non-null    object
 5   Age                491 non-null    int32
 6   Affiliate          491 non-null    object
 7   Height and Weight  491 non-null    object
 8   Points             491 non-null    int64
 9   21.1 Scores        491 non-null    object
 10  21.1 Reps          491 non-null    int32
 11  21.2 Scores        491 non-null    object
 12  21.2 Reps          491 non-null    int32
 13  21.3 Scores        491 non-null    object
 14  21.3 Reps          491 non-null    int32
 15  21.4 Scores        491 non-null    object
 16  Weight Lifted      491 non-null    object
 17  Height             491 non-null    object
 18  Weight             491 non-null    object
dtypes: int32(4), int64(2), object(13)
memory usage: 69.0+ KB

C:\Users\Matthew\AppData\Local\Temp\ipykernel_22796\2543708524.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  crossfitDF2['21.1 Reps'] = crossfitDF2['21.1 Reps'].astype(int)
C:\Users\Matthew\AppData\Local\Temp\ipykernel_22796\2543708524.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  crossfitDF2['21.2 Reps'] = crossfitDF2['21.2 Reps'].astype(int)
C:\Users\Matthew\AppData\Local\Temp\ipykernel_22796\2543708524.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  crossfitDF2['21.3 Reps'] = crossfitDF2['21.3 Reps'].astype(int)